# Generated by Django 4.2.16 on 2024-10-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_laboratorytestcategory_laboratorytest"),
    ]

    operations = [
        migrations.RenameField(
            model_name="laboratorytest",
            old_name="lab_category",
            new_name="category",
        ),
    ]
