# Generated by Django 4.2.16 on 2024-10-17 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_rename_lab_category_laboratorytest_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LaboratoryTest",
        ),
        migrations.DeleteModel(
            name="LaboratoryTestCategory",
        ),
    ]
